# Generated by Django 2.0.dev20170304171821 on 2017-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=64)),
            ],
        ),
    ]
