# Generated by Django 2.0.dev20170304171821 on 2017-04-23 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('tms', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('clientId', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('tms', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('clientId', models.CharField(max_length=64)),
                ('documentId', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=128)),
                ('tms', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SignatureDetail',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('signatureId', models.CharField(max_length=64)),
                ('part', models.CharField(max_length=256)),
                ('tms', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='clientId',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='tms',
            field=models.TimeField(default=datetime.datetime(2017, 4, 23, 4, 13, 47, 754306)),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(default='', max_length=64),
        ),
    ]
