# Generated by Django 2.0.dev20170304171821 on 2017-04-23 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170423_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='apikey',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='tms',
            field=models.TimeField(default=datetime.datetime(2017, 4, 23, 6, 0, 45, 946664)),
        ),
    ]
