# Generated by Django 2.0.dev20170304171821 on 2017-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170423_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tms',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tms',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='tms',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signaturedetail',
            name='tms',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tms',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
